name: BuildLinux

on: workflow_dispatch

jobs:
  buildAssets:
    uses: ./.github/workflows/build_assets.yml

  buildLinux-AppImage:
    needs: buildAssets
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.12"
      LINUX_TAG: "manylinux_2_28_x86_64"
    steps:
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install Packages (pip)
        run: pip install python-appimage

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nw-assets
          path: novelwriter/assets

      - name: Build AppImage
        run: python pkgutils.py build-appimage --linux-tag $LINUX_TAG --python-version $PYTHON_VERSION

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-AppImage
          path: dist_appimage
          if-no-files-found: error
          retention-days: 14
