name: BuildMacOS

on: workflow_dispatch

jobs:
  buildAssets:
    uses: ./.github/workflows/build_assets.yml

  buildMac-AMD64:
    needs: buildAssets
    # Stay on macos-12 due to https://github.com/create-dmg/create-dmg/issues/143
    runs-on: macos-12
    env:
      PYTHON_VERSION: "3.12"
      PACKAGE_ARCH: x86_64
      MINICONDA_ARCH: x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nw-assets
          path: novelwriter/assets

      - name: Build App Bundle
        run: ./setup/macos/build.sh $PYTHON_VERSION $PACKAGE_ARCH $MINICONDA_ARCH

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-AMD64-DMG
          path: dist_macos
          if-no-files-found: error
          retention-days: 14

  buildMac-M1:
    needs: buildAssets
    runs-on: macos-14
    env:
      PYTHON_VERSION: "3.12"
      PACKAGE_ARCH: aarch64
      MINICONDA_ARCH: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nw-assets
          path: novelwriter/assets

      - name: Build App Bundle
        run: ./setup/macos/build.sh $PYTHON_VERSION $PACKAGE_ARCH $MINICONDA_ARCH

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-M1-DMG
          path: dist_macos
          if-no-files-found: error
          retention-days: 14
